//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_prestamo
    {
        public int idPrestamoDetalle { get; set; }
        public int id_prestamo { get; set; }
        public int id_estado { get; set; }
        public int id_libro { get; set; }
        public Nullable<System.DateTime> fecha_devuelto { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual libro libro { get; set; }
        public virtual prestamo prestamo { get; set; }
    }
}
